### PR TITLE
feat: add compact mode

### PR DESCRIPTION
**Pull request by tuananhp-1844**
i add compact mode. you can check it and comment for you me know. thank you .
Peek 2019-10-08 23-34

### CODE REVIEW

**Comment by MarceauKa** [comment]
Interesting idea, but few things in my opinion:
1. Maybe using settings section for compact mode but your implementation is also smart.
2. I personally dislike using a controller and a route and storing the preference in php session, we could use browser local storage.
3. Icons are good but we can integrate the switch at a better place.
However thank you for your work!

**Comment by tuananhp-1844** [comment]
i use localstorage instead session. you can check it and commet.thank you

**Comment by MarceauKa** [comment]
Hm, I'll make some improvements before merging it. For now I don't want to use font awesome (maybe in the future but not with cloudflare cdn).

**Comment by MarceauKa** [comment]
Done differently in [1.2.15](https://github.com/MarceauKa/laravel-shaarli/releases/tag/1.2.15).
Thank you!

**Pull request closed without merging**
