### PR TITLE
fix: duplicate link

### PR DESCRIPTION
**Pull request by tuananhp-1844**
Check if a link is already shared when adding one. i fixed it!

### CODE REVIEW

**Comment by MarceauKa** [comment]
Thank you, I'll merge it soon :)

**Comment by MarceauKa** [comment]
I think it can be a good idea to use the parse method to display a message if the link already exists without submitting the form

**Comment by tuananhp-1844** [comment]
check it for me

**Comment by MarceauKa** [comment]
Released in [1.2.16](https://github.com/MarceauKa/laravel-shaarli/releases/tag/1.2.16)

**Pull request merged**
